version: '3.8'

services:
  taxi_project:
    image: angelfelizr/project.nyc.taxi:0.0.0.9000
    container_name: TaxiProject
    environment:
      - DISABLE_AUTH=true
      - RENV_PATHS_CACHE=/home/rstudio/.cache/R/renv/library/project.nyc.taxi-dd1eca8a/linux-ubuntu-jammy/R-4.4/x86_64-pc-linux-gnu
    ports:
      - "127.0.0.1:5555:8787"
    volumes:
      - /home/angelfeliz/Documents/r-projects:/home/rstudio
      - /home/angelfeliz/Documents/r-projects/r-lib-4.4:/usr/local/lib/R/site-library
      - /home/angelfeliz/Documents/r-projects/cache_4.4:/home/rstudio/.cache/R/renv/library/project.nyc.taxi-dd1eca8a/linux-ubuntu-jammy/R-4.4/x86_64-pc-linux-gnu
