flat_eda_functions.Rmd:
  path: dev/flat_eda_functions.Rmd
  state: active
  R:
  - R/compute_boxplot.R
  - R/count_pct.R
  - R/factor_weekday.R
  - R/fast_glimpse.R
  - R/join_zones.R
  - R/show_boxplot.R
  tests:
  - tests/testthat/test-fast_glimpse.R
  - tests/testthat/test-factor_weekday.R
  vignettes: []
  inflate:
    flat_file: dev/flat_eda_functions.Rmd
    vignette_name: .na
    open_vignette: true
    check: true
    document: true
    overwrite: ask
    vignettes: false
flat_functions.Rmd:
  path: dev/flat_functions.Rmd
  state: active
  R:
  - R/add_datetime_features.R
  - R/add_zone_description.R
  - R/apply_base_cleaning.R
  - R/compute_num_summary.R
  - R/count_pct.R
  - R/factor_weekday.R
  - R/is_arrow_con.R
  - R/sample_parquet.R
  - R/simulate_trips.R
  - R/bussiness-understanding-baselinesimulation.R
  - R/eda-functions-zonecodesarcgis.R
  tests:
  - tests/testthat/test-simulate_trips.R
  - tests/testthat/test-count_pct.R
  - tests/testthat/test-add_zone_description.R
  - tests/testthat/test-factor_weekday.R
  - tests/testthat/test-sample_parquet.R
  vignettes: []
  inflate:
    flat_file: dev/flat_functions.Rmd
    vignette_name: .na
    open_vignette: true
    check: false
    document: true
    overwrite: ask
    vignettes: false
