flat_business_understending.Rmd:
  path: dev/flat_business_understending.Rmd
  state: active
  R:
  - R/simulate_trips.R
  - R/defining-metric-s-base-line.R
  tests: tests/testthat/test-simulate_trips.R
  vignettes: vignettes/02-business-understanding.Rmd
  inflate:
    flat_file: dev/flat_business_understending.Rmd
    vignette_name: 02 - Business Understanding
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
    vignettes: false
flat_eda_functions.Rmd:
  path: dev/flat_eda_functions.Rmd
  state: active
  R:
  - R/compute_boxplot.R
  - R/count_pct.R
  - R/factor_weekday.R
  - R/fast_glimpse.R
  - R/join_zones.R
  - R/show_boxplot.R
  tests:
  - tests/testthat/test-fast_glimpse.R
  - tests/testthat/test-factor_weekday.R
  vignettes: []
  inflate:
    flat_file: dev/flat_eda_functions.Rmd
    vignette_name: .na
    open_vignette: true
    check: true
    document: true
    overwrite: ask
    vignettes: false
