---
title: "Simulate Trips"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

## SimulationStartDay

```{r function-SimulationStartDay}
#' Defines the start point for each day to simulate.
#'
#' This table is a random sample of all trips in 2023, generated using the `reservoir` method of duckdb with a seed of 3518, as described in `vignette("02-business-understanding")`.
#'
#' @format ## `SimulationStartDay`
#' A data frame with 60 rows and 22 columns:
#' \describe{
#'   \item{hvfhs_license_num}{The TLC license number of the HVFHS base or business. See Details.}
#'   \item{dispatching_base_num}{The TLC Base License Number of the base that dispatched the trip.}
#'   \item{originating_base_num}{Base number of the base that received the original trip request.}
#'   \item{request_datetime}{Date/time when passenger requested to be picked up.}
#'   \item{on_scene_datetime}{Date/time when driver arrived at the pick-up location (Accessible Vehicles-only).}
#'   \item{pickup_datetime}{The date and time of the trip pick-up.}
#'   \item{dropoff_datetime}{The date and time of the trip drop-off.}
#'   \item{PULocationID}{TLC Taxi Zone in which the trip began.}
#'   \item{DOLocationID}{TLC Taxi Zone in which the trip ended.}
#'   \item{trip_miles}{Total miles for passenger trip.}
#'   \item{trip_time}{Total time in seconds for passenger trip.}
#'   \item{base_passenger_fare}{Base passenger fare before tolls, tips, taxes, and fees.}
#'   \item{tolls}{Total amount of all tolls paid in trip.}
#'   \item{bcf}{Total amount collected in trip for Black Car Fund.}
#'   \item{sales_tax}{Total amount collected in trip for NYS sales tax.}
#'   \item{congestion_surcharge}{Total amount collected in trip for NYS congestion surcharge.}
#'   \item{airport_fee}{\$2.50 for both drop off and pick up at LaGuardia, Newark, and John F. Kennedy airports.}
#'   \item{tips}{Total amount of tips received from passenger.}
#'   \item{driver_pay}{Total driver pay (not including tolls or tips and net of commission, surcharges, or taxes).}
#'   \item{shared_request_flag}{Did the passenger agree to a shared/pooled ride? (Y/N)}
#'   \item{shared_match_flag}{Did the passenger share the vehicle with another passenger? (Y/N)}
#'   \item{access_a_ride_flag}{Was the trip administered on behalf of the Metropolitan Transportation Authority (MTA)? (Y/N)}
#'   \item{wav_request_flag}{Did the passenger request a wheelchair-accessible vehicle (WAV)? (Y/N)}
#'   \item{wav_match_flag}{Did the trip occur in a wheelchair-accessible vehicle (WAV)? (Y/N)}
#' }
#' @source <https://www.nyc.gov/site/tlc/about/tlc-trip-record-data.page>
"SimulationStartDay"
```

## simulate_without_model

```{r function-simulate_without_model}

simulate_without_model <- function(conn,
                                   start_point,
                                   parquet_files,
                                   valid_zones) {
  
  stopifnot("MeanDistance must be in the database" = "MeanDistance" %chin% DBI::dbListTables(conn))
  
  start_point
  
}
```

### tests

```{r tests-simulate_without_model}
describe("simulate_without_model()",{
  
  con_temp <- DBI::dbConnect(duckdb::duckdb())
  on.exit(DBI:dbDisconnect(con_temp), add = TRUE)
  
  DBI::dbListTables(con_temp)
  
  DBI::dbWriteTable(con, "iris_table", iris)
  
  
  it("The TLC license number (taxi company) needs to keep constant",{
    
  })
  
  
  it("Only wheelchair-accessible vehicles can accept trips with that request",{
    
  })
  
  
  
  it("They will take their last trip after working 8 hours",{
    
  })
  
  
  it("They have a 30 minutes break after 4 hours working",{
    
  })
  
  
  describe("The taxis will find trips based on their time waiting",{
  
      
    it("0-1 Minute: Search within a 1-mile radius and acept first trip",{
      
    })
    
    
    it("1-3 Minutes: Expand search to a 3-mile radius if no trip is found and acept first trip",{
      
    })
    
    
    it("3-5 Minutes: Expand search to a 5-mile radius if still no trip is found and acept first trip",{
      
    })
    
    
    it(">5 Minutes: Expand search to a 7-mile radius if no trip is found yet and acept first trip",{
      
    })
    
  })
  
  
})
```

