# WARNING - Generated by {fusen} from dev/flat_functions.Rmd: do not edit by hand

test_that("country was created",{
  
  original_dt <- data.table::data.table(
    hvfhs_license_num = c("HV0002",
                          "HV0003",
                          "HV0004",
                          "HV0005",
                          "No Found")
  )
  
  ## Running the function
  clean_dt <- set_initial_cleaning(data.table::copy(original_dt))
  
  ## The original column must be removed
  expect_false(any(names(clean_dt) == "hvfhs_license_num"))
  
  ## The company column was translated with the correct values
  expect_equal(
    clean_dt$company,
    c("Juno", "Uber", "Via", "Lyft", "Other")
  )
  
})


test_that("dispatching_base_num and originating_base_num only can keep some values",{
  
  ## Defining the relation to expect
  start_values <- c("B03404", "B03406", NA_character_, " ", "B00000")
  end_values <- c("B03404", "B03406", "Missing", "Missing", "Other")
  
  ## Saving the raw data example
  original_dt <- data.table::data.table(
    dispatching_base_num = start_values,
    originating_base_num = start_values
  )
  
  ## Running the function
  clean_dt <- set_initial_cleaning(data.table::copy(original_dt))
  
  ## Validating the results on each column
  expect_equal(clean_dt$dispatching_base_num, end_values)
  expect_equal(clean_dt$originating_base_num, end_values)
  
})

test_that("access_a_ride_flag shouldn't have any empty value",{
  
  ## Saving the raw data example
  original_dt <- data.table::data.table(
    access_a_ride_flag = c("N", " ")
  )
  
  ## Running the function
  clean_dt <- set_initial_cleaning(data.table::copy(original_dt))
  
  ## Validating the results
  expect_equal(clean_dt$access_a_ride_flag, c("N", "Missing"))
  
})


test_that("Cleaning request_datetime and dropoff_datetime",{
  
  ## Saving the raw data example
  original_dt <- data.table::data.table(
    request_datetime = c(lubridate::make_datetime(2024,05,18,8, 30),
                         lubridate::make_datetime(2024,05,18,8, 30)),
    dropoff_datetime = c(lubridate::make_datetime(2024,05,18,9, 0),
                         #This happened before the start time
                         lubridate::make_datetime(2024,05,18,5, 30))
  )
  
  ## Creating a table with all problems solved
  expected_dt <- data.table::data.table(
    request_datetime = c(lubridate::make_datetime(2024,05,18,8, 30),
                         lubridate::make_datetime(2024,05,18,5, 30)),
    dropoff_datetime = c(lubridate::make_datetime(2024,05,18,9, 0),
                         lubridate::make_datetime(2024,05,18,8, 30)),
    trip_hours = c(0.5, 3)
  )
  
  ## Running the function
  clean_dt <- set_initial_cleaning(data.table::copy(original_dt))
  
  ## Any request time shouldn't be larger than the drop off time
  expect_true(clean_dt[request_datetime > dropoff_datetime, .N] == 0L)
  
  ## We are moving the date around
  expect_equal(clean_dt,expected_dt)
  
  ## All differences must be positive
  expect_true(all(clean_dt$trip_hours >= 0))
})


test_that("Any driver_pay can keep as negative",{
  
  ## Saving the raw data example
  original_dt <- data.table::data.table(
    driver_pay = c(5, 8, 0, -4, -80)
  )
  
  ## Running the function
  clean_dt <- set_initial_cleaning(data.table::copy(original_dt))
  
  ## Validating the results
  expect_equal(clean_dt$driver_pay, c(5, 8, 0, NA_real_, NA_real_))
  
})

