# WARNING - Generated by {fusen} from dev/flat_business_understending.Rmd: do not edit by hand


# Defining some zone context
valid_zones <- 1:3
closest_zones <- c(2L, 1L, 2L)
names(closest_zones) <- valid_zones
borough_zones <- data.frame(
  LocationID = valid_zones,
  id_list = I(list(valid_zones, valid_zones, valid_zones))
)

# Defining start point
start_datetime <- lubridate::make_datetime(2023L, 5L, 18L, 8L)
start_zone <- 1L

# Let's check trips from at 3 levels
# 1. Starting in the same zone
# 2. Starting in the closest zone
# 3. Starting in the farthest zone
valid_trips <- data.frame(
  year = 2023L,
  month = 5L,
  PULocationID = c(1L, 2L, 3L),
  DOLocationID = c(3L, 1L, 1L),
  request_datetime = c(
   start_datetime + lubridate::minutes(2L),
   start_datetime + lubridate::minutes(20L + 7L),
   start_datetime + lubridate::minutes(37L + 14L)
  ),
  dropoff_datetime = c(
   start_datetime + lubridate::minutes(20L),
   start_datetime + lubridate::minutes(37L),
   lubridate::make_datetime(2023L, 5L, 18L, 9L, 1L)
  ),
  driver_pay = 10,
  tips = 2 
)

# Defining 2 invalid trips
# 1. The trip goes after the 6 min in same zone
# 2. The trip is too far from second iteration
trips_to_omit <- data.frame(
  year = 2023L,
  month = 5L,
  PULocationID = c(1L, 3L),
  DOLocationID = c(3L, 1L),
  
  request_datetime = c(
   start_datetime + lubridate::minutes(2L + 6L),
   start_datetime + lubridate::minutes(20L + 7L)
  ),
  dropoff_datetime = c(
   start_datetime + lubridate::minutes(26L),
   start_datetime + lubridate::minutes(37L)
  ),
  driver_pay = 10,
  tips = 2 
)


testthat::test_that("The simulation is taking the correct options",{
  
  testthat::expect_equal(
    simulate_trips(rbind(valid_trips, trips_to_omit),
                   start_datetime = start_datetime,
                   start_zone = start_zone,
                   minutes_next_trip = 6L,
                   end_datetime = start_datetime + lubridate::hours(1L),
                   valid_end_zones = valid_zones,
                   closest_zone = closest_zones,
                   borough_zones = borough_zones),
    simulate_trips(valid_trips,
                   start_datetime = start_datetime,
                   start_zone = start_zone,
                   minutes_next_trip = 6L,
                   end_datetime = start_datetime + lubridate::hours(1L),
                   valid_end_zones = valid_zones,
                   closest_zone = closest_zones,
                   borough_zones = borough_zones) 
  )
  
})


testthat::test_that("Missing column stop is working",{
  
  testthat::expect_error({
    simulate_trips(valid_trips[!names(valid_trips) %in% c("driver_pay", "tips")],
                   start_datetime = start_datetime,
                   start_zone = start_zone,
                   minutes_next_trip = 6L,
                   end_datetime = start_datetime + lubridate::hours(1L),
                   valid_end_zones = valid_zones,
                   closest_zone = closest_zones,
                   borough_zones = borough_zones) 
  })
  
})

