# WARNING - Generated by {fusen} from dev/flat_functions.Rmd: do not edit by hand

test_that("The prob is working",{
  df <- data.frame(x = 1:100)
  file_path <- tempfile(fileext = ".parquet")
  
  arrow::write_parquet(df, file_path)
  
  taken_sample <- sample_parquet(file_path)
  
  expect_equal(nrow(taken_sample),5L)
  
  file.remove(file_path)
})

test_that("The zone is working",{
  
  df <- data.frame(x = 1:100,
                        PULocationID = rep(1:5, each = 20),
                        DOLocationID = rep(5:1, each = 20))
  
  file_path <- tempfile(fileext = ".parquet")
  
  arrow::write_parquet(df, file_path)
  
  taken_sample <- sample_parquet(file_path,
                                 valid_zones = 3L,
                                 prob = 0.10)
  
  expect_equal(nrow(taken_sample), 2L)
  
  expect_true(all(taken_sample$PULocationID == 3L))
  
  expect_true(all(taken_sample$DOLocationID == 3L))
  
  file.remove(file_path)
})
