# WARNING - Generated by {fusen} from dev/flat_functions.Rmd: do not edit by hand

test_that("The prob is working",{
  df <- data.frame(x = 1:100)
  file_path <- tempfile(fileext = ".parquet")
  
  arrow::write_parquet(df, file_path)
  
  taken_sample <- sample_parquet(file_path)
  
  expect_equal(nrow(taken_sample),5L)
  
  file.remove(file_path)
})

test_that("The zone is working",{
  
  withr::local_seed(100)
  
  df <- data.frame(x = 1:100,
                   PULocationID = sample.int(3L, 100, TRUE),
                   DOLocationID = sample.int(3L, 100, TRUE))
  
  file_path <- withr::local_tempfile(fileext = ".parquet")
  
  arrow::write_parquet(df, file_path)
  
  valid_zones <-  c(2L, 3L)
  
  taken_sample <- sample_parquet(file_path,
                                 valid_zones = valid_zones,
                                 prob = 0.10)
  
  # Start and End in valid zone
  expect_true(all(taken_sample$PULocationID %in% valid_zones))
  expect_true(all(taken_sample$DOLocationID %in% valid_zones))
  
  # We don't need NA zones
  expect_false(any(is.na(taken_sample$PULocationID)))
  expect_false(any(is.na(taken_sample$DOLocationID)))
  
  # We don't always end where we started
  expect_true(any(taken_sample$DOLocationID != taken_sample$PULocationID))
})
