# WARNING - Generated by {fusen} from dev/flat_functions.Rmd: do not edit by hand


test_that("x must be numeric",{
  testthat::expect_error(factor_weekday(c("Mon", 5)))
})

test_that("x must have values from 1 to 7",{
  testthat::expect_warning(factor_weekday(c(10, 5)))
})

