# WARNING - Generated by {fusen} from dev/flat_functions.Rmd: do not edit by hand


test_that("Several zones represed as a single location", {
  
  clean_dt <- clean_zone_manually(ZoneCodesArcgis)
  
  expect_equal(
    clean_dt[, .(zone_count = data.table::uniqueN(Zone)),
             c("long", 'lat')
    ][zone_count > 1L, .N],
    0L
  )
  
})

