# WARNING - Generated by {fusen} from dev/flat_functions.Rmd: do not edit by hand

test_that("The map works in all situations",{
  
  # The must basic plot
  expect_no_error({
    plot_map(
      ZoneCodesArcgis,
      lng_var = "long",
      lat_var = "lat"
    )
  })
  
  # Adding color
  expect_no_error({
    plot_map(
      ZoneCodesArcgis,
      lng_var = "long",
      lat_var = "lat",
      color = "red"
    )
  })
  
  # Adding clusters
  expect_no_error({
    plot_map(
      ZoneCodesArcgis,
      lng_var = "long",
      lat_var = "lat",
      cluster_points = TRUE
    )
  })
    
  # Adding palette
  expect_no_error({
    plot_map(
      ZoneCodesArcgis,
      lng_var = "long",
      lat_var = "lat",
      color_var = "Borough",
      color_palette = c('Manhattan' = '#e41a1c',
                        'Queens' = '#377eb8',
                        'Brooklyn'= '#4daf4a')
    )
  })
  
})


test_that("The map shows informative errors",{
  
  # The must basic plot
  expect_error({
    plot_map(
      ZoneCodesArcgis,
      lng_var = "long",
    )
  },
  regexp = "no default")
  
  expect_error({
    plot_map(
      ZoneCodesArcgis,
      lng_var = "long",
      lat_var = "lat_error"
    )
  },
  regexp = "can not be found")
    
  # Adding palette
  expect_error({
    plot_map(
      ZoneCodesArcgis,
      lng_var = "long",
      lat_var = "lat",
      color_palette = c('Manhattan' = '#e41a1c',
                        'Queens' = '#377eb8',
                        'Brooklyn'= '#4daf4a')
    )
  },
  regexp = "you also need to define")
  
  
  expect_error({
    plot_map(
      ZoneCodesArcgis,
      lng_var = "long",
      lat_var = "lat",
      color_var = "error_col",
      color_palette = c('Manhattan' = '#e41a1c',
                        'Queens' = '#377eb8',
                        'Brooklyn'= '#4daf4a')
    )
  },
  regexp = "can not be found")
  
  
  expect_error({
    plot_map(
      ZoneCodesArcgis,
      lng_var = "long",
      lat_var = "lat",
      color_var = "Borough",
      color_palette = c('ERROR_VALUE' = '#e41a1c',
                        'Queens' = '#377eb8',
                        'Brooklyn'= '#4daf4a')
    )
  },
  regexp = "couldn't be found")
  
  
  expect_error({
    plot_map(
      ZoneCodesArcgis,
      lng_var = "long",
      lat_var = "lat",
      label_var = "error_var"
    )
  },
  regexp = "can not be found")
  
})

