# WARNING - Generated by {fusen} from dev/flat_functions.Rmd: do not edit by hand

test_that("The sample plan shouldn't be larger than number of rows in original data",{
  expect_error({
    data.frame(x = rep(1:5, each = 2)) |>
      plan_sample_by_group(x , size = 10)
  })
})
