# WARNING - Generated by {fusen} from dev/flat_eda_functions.Rmd: do not edit by hand


df <- data.frame(num = runif(10),
                 char = LETTERS[1:10],
                 factor = factor(LETTERS[1:10], levels = LETTERS[1:10]),
                 dates = seq(from = as.Date("2024-01-01"), 
                             by = "month", length.out = 10)) 

testthat::test_that("We don't method for data.frame",{
  testthat::expect_error(
    glimpse(df)
  )
})

