# WARNING - Generated by {fusen} from dev/flat_functions.Rmd: do not edit by hand


test_that("The add_zone_description is working",{
  
  # Defing the data to use
  withr::local_seed(123)
  
  base_data <- data.table::data.table(
    start_id = 1:5,
    end_id = sample.int(5, 5),
    value = seq(50, length.out = 5, by = 50)
  )
  
  zone_description <- data.table::data.table(
    id = 1:5,
    City = LETTERS[1:5],
    Zone = tail(LETTERS, 5L)
  )
  
  
  ## Running the function

  # Running the function with defaults
  final_dt <-
    add_zone_description(base_data,
                         zone_description,
                         start_id_col = "start_id",
                         end_id_col = "end_id",
                         zone_id_col = "id")
  
  # Running the function keeping all columns
  final_dt_id <-
    add_zone_description(base_data,
                         zone_description,
                         start_id_col = "start_id",
                         end_id_col = "end_id",
                         zone_id_col = "id",
                         keep_dt_id_cols = TRUE)
  
  # Validating column results
  expect_equal(names(final_dt),
               c("start_city",
                 "start_zone",
                 "end_city",
                 "end_zone",
                 "value"))

  expect_equal(names(final_dt_id),
               c("start_id",
                 "start_city",
                 "start_zone",
                 "end_id",
                 "end_city",
                 "end_zone",
                 "value"))
  
  # Making sure weren't adding rows
  expect_equal(nrow(final_dt), 5L)
  expect_equal(nrow(final_dt_id), 5L)
  
  
  # Validating errors
  
  # We cannot missing start_id_col
  expect_error(add_zone_description(base_data,
                                    zone_description,
                                    start_id_col = "no valid",
                                    end_id_col = "end_id",
                                    zone_id_col = "id"))
  expect_error(add_zone_description(base_data,
                                    zone_description,
                                    start_id_col = c("start_id", "start_id"),
                                    end_id_col = "end_id",
                                    zone_id_col = "id"))
  
  # We cannot missing end_id_col
  expect_error(add_zone_description(base_data,
                                    zone_description,
                                    start_id_col = "start_id",
                                    end_id_col = "no valid",
                                    zone_id_col = "id"))
  expect_error(add_zone_description(base_data,
                                    zone_description,
                                    start_id_col = "start_id",
                                    end_id_col = c("end_id", "end_id"),
                                    zone_id_col = "id"))
  
  # We cannot missing zone_id_col
  expect_error(add_zone_description(base_data,
                                    zone_description,
                                    start_id_col = "start_id",
                                    end_id_col = "end_id",
                                    zone_id_col = "no valid"))
  expect_error(add_zone_description(base_data,
                                    zone_description,
                                    start_id_col = "start_id",
                                    end_id_col = "end_id",
                                    zone_id_col = c("id", "id")))
})
