# WARNING - Generated by {fusen} from dev/flat_functions.Rmd: do not edit by hand

#' Add more features to explain a date
#'
#' @param df A data.frame with datetime column to use.
#' @param date_col A string to define the column to be use
#' 
#' @return A data.frame with the new features.
#' @export
#' 
#' @importFrom rlang sym
#' @importFrom lubridate cyclic_encoding
#' @importFrom recipes recipe step_date step_time step_holiday prep bake
#' @importFrom timeDate listHolidays
#' @importFrom data.table setattr
#'
#' @examples
#' data.frame(profit_rate = 15,
#'            x = as.POSIXct("2024-05-18 08:00:15"),
#'            y = as.POSIXct("2024-07-04 08:00:15")) |>
#'   add_datetime_features(date_col = "x") |>
#'   add_datetime_features(date_col = "y")
add_datetime_features <- function(df, date_col) {
  
  col_expr <- rlang::sym(date_col)
  
  cyclic_df <- 
    lubridate::cyclic_encoding(df[[date_col]],
                               periods = c("day", "week", "month")) |>
    as.data.frame()
  
  data.table::setattr(cyclic_df, "names", paste0(date_col, "_", names(cyclic_df)))
  
  df_cleaned <- cbind(df, cyclic_df)
  
  df_cleaned <-
    recipes::recipe(profit_rate ~ .,
                    data = df_cleaned) |>
    recipes::step_date({{col_expr}},
                       features = c("dow",
                                    "doy",
                                    "week",
                                    "month",
                                    "decimal",
                                    "quarter",
                                    "semester")) |>
    recipes::step_time({{col_expr}},
                       features = c("am", 
                                    "hour",
                                    "hour12",
                                    "decimal_day")) |>
    recipes::step_holiday({{col_expr}},
                          holidays = timeDate::listHolidays("^US"),
                          keep_original_cols = FALSE) |>
    recipes::prep(training = df_cleaned) |>
    recipes::bake(new_data = NULL)
  
  return(df_cleaned)
  
}
