# WARNING - Generated by {fusen} from dev/flat_functions.Rmd: do not edit by hand

#' Apply the transformations based on initial EDA
#'
#' @param dt A data.table with all columns of data and after translating the code zone with their meaning.
#'
#' @return A data.table
#' @export
#' 
#' @importFrom data.table fcase fifelse %like% %between%
#'
#' @examples
#'
#' data.table::data.table(hvfhs_license_num = "HV0004",
#'                        dispatching_base_num = "HOLA",
#'                        originating_base_num = NA_character_,
#'                        access_a_ride_flag = "",     
#'                        shared_request_flag = "Y",
#'                        shared_match_flag = "Y",
#'                        wav_request_flag = "Y",
#'                        wav_match_flag = "Y",
#'                        start_borough = "Manhattan",
#'                        end_borough = "Brooklyn",
#'                        start_service_zone = "Boro Zone",
#'                        end_service_zone = "Yellow Zone",
#'                        start_zone = "1",
#'                        end_zone = "2",
#'                        base_passenger_fare = 800,
#'                        trip_miles = 250,
#'                        request_datetime = as.POSIXct("2022-05-18 7:25:00"), 
#'                        dropoff_datetime = as.POSIXct("2022-05-18 8:15:00"),
#'                        tips = 500,
#'                        driver_pay = 800) |>
#'   apply_base_cleaning()
#'
apply_base_cleaning <- function(dt) {
  
  # Transforming columns into factors
  
  dt[, company := 
       data.table::fcase(hvfhs_license_num == "HV0002", "Juno",
                         hvfhs_license_num == "HV0003", "Uber",
                         hvfhs_license_num == "HV0004", "Via",
                         hvfhs_license_num == "HV0005", "Lyft") |>
       factor(levels = c("Juno", "Uber", "Via", "Lyft"))]
  
  dt[, dispatching_base_num :=
       data.table::fifelse(dispatching_base_num %chin% c("B03404", "B03406"),
                           dispatching_base_num,
                           "Other") |>
       factor(levels = c("B03404", "B03406", "Other"))]
  
  dt[, originating_base_num := 
       data.table::fcase(is.na(dispatching_base_num), "Missing", 
                         dispatching_base_num == "B03404", "B03404",
                         default = "Other") |>
       factor(levels = c("B03404", "Other", "Missing"))]
  
  
  # Selecting column groups
  
  col_names <- names(dt)
  flag_cols <- grep("flag$", col_names, value = TRUE)
  borough_cols <- grep("borough$", col_names, value = TRUE)
  service_zone_cols <- grep("service_zone$", col_names, value = TRUE)
  
  
  # Formating columns by group
  
  dt[, (flag_cols) := lapply(
    .SD,
    FUN = \(x) data.table::fifelse(x %chin% c("Y", "N"), x, "Missing") |>
      factor(levels = c("Y", "N", "Missing"))
  ),
  .SDcols = flag_cols]
  

  dt[, (borough_cols) := lapply(
    .SD,
    FUN = \(x) factor(x, levels = c("Manhattan", "Brooklyn", "Queens"))
  ),
  .SDcols = borough_cols]


  dt[, (service_zone_cols) := lapply(
    .SD,
    FUN = \(x) factor(x, levels = c("Boro Zone", "Yellow Zone", "Airports"))
  ),
  .SDcols = service_zone_cols]

  
  # Defining same place
  
  dt[, same_borough := start_borough == end_borough]
  dt[, same_service_zone := start_service_zone == end_service_zone]
  dt[, same_zone := start_zone == end_zone]
  
  
  # Adding numeric columns
  
  dt[, trip_minutes := 
       difftime(dropoff_datetime,
                request_datetime,
                units = "mins") |>
       as.integer()]
    
    dt[, profit_rate := 
         (driver_pay + tips) / (trip_minutes / 60L)]

    
  # Defining columns to keep
  
    cols_to_keep <- c(
      "company",
      "dispatching_base_num",
      "originating_base_num",
      flag_cols,
      borough_cols,
      service_zone_cols,
      "start_lat",
      "start_long",
      "end_lat",
      "end_long",
      "same_borough",
      "same_service_zone",
      "same_zone",
      "base_passenger_fare",
      "trip_miles",
      "request_datetime",
      "dropoff_datetime",
      "trip_minutes",
      "tips",
      "driver_pay",
      "profit_rate"
    )
    
  return(dt[, ..cols_to_keep])
  
}
