# WARNING - Generated by {fusen} from dev/flat_functions.Rmd: do not edit by hand

#' Apply the transformations based on initial EDA
#'
#' @param dt A data.table with all columns of data and after translating the code zone with their meaning.
#'
#' @return A data.table
#' @export
#' 
#' @importFrom data.table fcase fifelse %like% %between%
#'
#' @examples
#'
#' data.table::data.table(hvfhs_license_num = "HV0004",
#'                        dispatching_base_num = "HOLA",
#'                        originating_base_num = NA_character_,
#'                        access_a_ride_flag = "",     
#'                        shared_request_flag = "Y",
#'                        shared_match_flag = "Y",
#'                        wav_request_flag = "Y",
#'                        wav_match_flag = "Y",
#'                        start_borough = "Manhattan",
#'                        end_borough = "Brooklyn",
#'                        start_service_zone = "Boro Zone",
#'                        end_service_zone = "Yellow Zone",
#'                        start_zone = "1",
#'                        end_zone = "2",
#'                        base_passenger_fare = 800,
#'                        trip_miles = 250,
#'                        request_datetime = as.POSIXct("2022-05-18 7:25:00"), 
#'                        dropoff_datetime = as.POSIXct("2022-05-18 8:15:00"),
#'                        tips = 500,
#'                        driver_pay = 800) |>
#'   apply_base_cleaning()
#'
apply_base_cleaning <- function(dt) {

  dt_cleaned <-
    dt[,.(company = 
            data.table::fcase(hvfhs_license_num == "HV0002", "Juno",
                              hvfhs_license_num == "HV0003", "Uber",
                              hvfhs_license_num == "HV0004", "Via",
                              hvfhs_license_num == "HV0005", "Lyft") |>
            factor(levels = c("Juno", "Uber", "Via", "Lyft")),
          
          dispatching_base_num =
            data.table::fifelse(dispatching_base_num %chin% c("B03404", "B03406"),
                                dispatching_base_num,
                                "Other") |>
            factor(levels = c("B03404", "B03406", "Other")),
          
          originating_base_num = 
            data.table::fcase(is.na(dispatching_base_num), "Missing", 
                              dispatching_base_num == "B03404", "B03404",
                              default = "Other") |>
            factor(levels = c("B03404", "Other","Missing")),
          
          
          access_a_ride_flag = 
            data.table::fifelse(!access_a_ride_flag %like% "//w", 
                                "Missing", 
                                access_a_ride_flag) |>
            factor(levels = c("Y", "N", "Missing")),
          
          shared_request_flag = 
            factor(shared_request_flag,
                   levels = c("Y", "N")),
          shared_match_flag = 
            factor(shared_match_flag,
                   levels = c("Y", "N")),
          wav_request_flag = 
            factor(wav_request_flag,
                   levels = c("Y", "N")),
          wav_match_flag = 
            factor(wav_match_flag,
                   levels = c("Y", "N")),
          
          start_borough = 
            factor(start_borough,
                   levels = c("Manhattan", "Brooklyn", "Queens")),
          end_borough = 
            factor(end_borough,
                   levels = c("Manhattan", "Brooklyn", "Queens")),
          same_borough = start_borough == end_borough, 
          
          start_service_zone = 
            factor(start_service_zone,
                   levels = c("Boro Zone", "Yellow Zone", "Airports")),
          end_service_zone = 
            factor(end_service_zone,
                   levels = c("Boro Zone", "Yellow Zone", "Airports")),
          same_service_zone = start_service_zone == end_service_zone,
          
          start_zone = factor(start_zone),
          end_zone = factor(end_zone),
          same_zone = start_zone == end_zone,
          
          request_datetime,
          
          # Paying more that 750 dollars or 
          # less than 0 don't make sense
          base_passenger_fare = 
            data.table::fifelse(base_passenger_fare %between% c(0, 750),
                                base_passenger_fare,
                                NA_real_),
          
          # Having trips longer that 200 miles doesn't make sense
          trip_miles =
            data.table::fifelse(trip_miles %between% c(0, 200),
                                trip_miles,
                                NA_real_),
          
          trip_minutes = 
            difftime(dropoff_datetime,
                     request_datetime,
                     units = "mins") |>
            as.integer() |>
            # More that 3 hours is too much time
            # and we can not use negative times
            (\(x) data.table::fifelse(x %between% c(0, 60*3), x, NA_integer_))(),
          
          tips,
          
          # Paying more that 750 dollars or 
          # less than 0 don't make sense
          driver_pay = 
            data.table::fifelse(driver_pay %between% c(0, 750),
                                driver_pay,
                                NA_real_))]
  
    dt_cleaned[, profit_rate := 
               (driver_pay + tips) / (trip_minutes / 60)]
  
  
  return(dt_cleaned[])
  
}
