# WARNING - Generated by {fusen} from dev/flat_functions.Rmd: do not edit by hand

#' Calculates all values need to describe
#' 
#' Calculates of values needed to create a boxplot.
#'
#' @param x A data.frame or an arrow connection
#' @param value A column vector to summarize
#' 
#' @importFrom dplyr filter summarize mutate select collect
#'
#' @return A data.frame with summary values
#' @export
#'
#' @examples
#'
#' data.frame(x = rnorm(200, mean = 5)) |>
#'   arrow::arrow_table() |>
#'   compute_num_summary(x)
#'
compute_num_summary <- function(x, value){

  summary <-
    dplyr::filter(x,
                  !is.na({{value}})) |>
    dplyr::summarize(min_value = min({{value}}),
                     q1 = quantile({{value}}, 0.25),
                     q2 = median({{value}}),
                     q3 = quantile({{value}}, 0.75),
                     max_value = max({{value}})) |>
    dplyr::mutate(lower_whisker = q1 - 1.5*(q3 - q1),
                  higher_whisker = q3 + 1.5*(q3 - q1)) |>
    dplyr::select(min_value,
                  lower_whisker,
                  q1,
                  q2,
                  q3,
                  higher_whisker,
                  max_value)
  
  if(inherits(x, "ArrowObject") | inherits(x, "arrow_dplyr_query")){
    summary <- dplyr::collect(summary)
  }

  return(summary)
}
