# WARNING - Generated by {fusen} from dev/flat_functions.Rmd: do not edit by hand

#' Counts rows based con columns provided
#' 
#' It counts the number rows where each unique value repeated in the columns 
#' selected arranging there results in descent order and adds a percentage 
#' column after collecting the results from `arrow`.
#'
#' @param x A lazy data frame arrow connection.
#' @param ... Variables to group by
#' @param wt  If a variable, computes sum(wt) for each group.
#' @param sort If TRUE, will show the largest groups at the top.
#' @param digits Integer indicating the number of decimal places
#'
#' @return A data.frame
#' @export
#'
#' @examples
#' set.seed(1234)
#'
#' arrow_con <- 
#'   data.frame(char1 = sample(LETTERS[1:3], 100, replace = TRUE),
#'              char2 = sample(LETTERS[4:6], 100, replace = TRUE)) |>
#'   arrow::arrow_table()
#'
#' # One var
#' count_pct(arrow_con, char1)
#'
#' # Two vars
#' dt1 <-count_pct(arrow_con, char1, char2)
#' dt1
#'
#' # You can use the wt function
#' count_pct(dt1, char1, wt = n)
count_pct <- function(x, ..., wt = NULL,  sort = TRUE, digits = 3L){
  
  grouping_vars_expr <- rlang::quos(...)
  wt_expr <- rlang::enquo(wt)
  
  counted_data <-
    if(!is.null(wt_expr)){
      dplyr::count(x,!!! grouping_vars_expr , wt = {{wt}}, sort = sort)
    }else{
      dplyr::count(x,!!! grouping_vars_expr, sort = sort)
    }
  
  
  if(is_arrow_con(x)){
    counted_data <- dplyr::collect(counted_data)
  }
  
  data.table::setDT(counted_data)
  
  counted_data[, pct := round(n / sum(n), digits)]
  
  counted_data[, pct_cumulative := cumsum(pct)]
  
  return(counted_data[])

}
