# WARNING - Generated by {fusen} from dev/flat_functions.Rmd: do not edit by hand

#' Counts rows based con columns provided
#' 
#' It counts the number rows where each unique value repeated in the columns 
#' selected arranging there results in descent order and adds a percentage 
#' column after collecting the results from `arrow`.
#'
#' @param x A lazy data frame arrow connection.
#' @param ... Variables to group by
#' @param wt  If a variable, computes sum(wt) for each group.
#' @param sort If TRUE, will show the largest groups at the top.
#' 
#' @importFrom dplyr count collect
#' @importFrom rlang quos
#' @importFrom data.table setDT `:=`
#'
#' @return A data.frame
#' @export
#'
#' @examples
#' set.seed(1234)
#'
#' arrow_con <- 
#'   data.frame(char1 = sample(LETTERS[1:3], 100, replace = TRUE),
#'              char2 = sample(LETTERS[4:6], 100, replace = TRUE)) |>
#'   arrow::arrow_table()
#'
#' count_pct(arrow_con, char1)
#' count_pct(arrow_con, char2)
#' count_pct(arrow_con, char1, char2)
count_pct <- function(x, ..., wt = NULL,  sort = TRUE){
  
  grouping_vars_expr <- rlang::quos(...)

  counted_data <-
    if(!is.null(wt)){
      dplyr::count(x,!!! grouping_vars_expr , wt = wt, sort = sort)
    }else{
      dplyr::count(x,!!! grouping_vars_expr, sort = sort)
    }
  
  
  if(is_arrow_con(x)){
    counted_data <- dplyr::collect(counted_data)
  }
  
  data.table::setDT(counted_data)
  
  counted_data[, pct := round(n / sum(n), 3)]
  
  counted_data[, pct_cumulative := cumsum(pct)]
  
  return(counted_data[])

}
