# WARNING - Generated by {fusen} from dev/flat_functions.Rmd: do not edit by hand

#' ZoneCodesArcgis
#'
#' Describe the locations used in the main data.
#'
#' @format A data frame of 7 variables:
#' \describe{
#'   \item{ LocationID }{ An unique id realted to each location}
#'   \item{ Borough }{ Borough for the location }
#'   \item{ Zone }{ Zone for the location }
#'   \item{ service_zone }{ Define the zone type }
#'   \item{ Address }{ A complete address for each location }
#'   \item{ lat }{ A latitute estimation based on Address }
#'   \item{ long }{ A longitute estimation based on Address }
#' }
#' @source TLC Trip Record Data and Arcgis
"ZoneCodesArcgis"
