# WARNING - Generated by {fusen} from dev/flat_eda_functions.Rmd: do not edit by hand


#' glimpse for arrow connections
#' 
#' Shows the class related to each column without loading the data into memory. 
#'
#' @param x an arrow connection
#' 
#' @importFrom scales comma
#'
#' @return The schema related to the connection
#' @export
#'
#' @examples
#'
#' df <- data.frame(num = runif(10),
#'                  char = LETTERS[1:10],
#'                  factor = factor(LETTERS[1:10], levels = LETTERS[1:10]),
#'                  dates = seq(from = as.Date("2024-01-01"), 
#'                              by = "month", length.out = 10))
#'
#' arrow::arrow_table(df) |> fast_glimpse()
fast_glimpse <- function(x){
  
  stopifnot("x is not an arrow connection" = 
              inherits(x, "ArrowObject") | inherits(x, "arrow_dplyr_query"))

  schm <- x$.data$schema

  col_types <- sapply(

    x$selected_columns,

    FUN = function(expr) {
      name <- expr$field_name
      if (nzchar(name)) {
        schm$GetFieldByName(name)$type$ToString()
      }
      else {
        expr$type(schm)$ToString()
      }

    })


  fields <- paste(
    names(col_types),
    col_types,
    sep = ": ",
    collapse = "\n"
  )

  cat(
    paste0("FileSystemDataset (query)\n",
           scales::comma(nrow(x)), " rows x ",
           scales::comma(ncol(x)), " columns\n\n",
           fields)
  )
  
  invisible(schm)
}

