# WARNING - Generated by {fusen} from dev/flat_functions.Rmd: do not edit by hand

#' Validate if is an arrow table
#'
#' @param x An object
#'
#' @return A boolean variable
#' @noRd
is_arrow_con <- function(x){
  inherits(x, "ArrowObject") | 
    inherits(x, "arrow_dplyr_query")
}
