# WARNING - Generated by {fusen} from dev/flat_functions.Rmd: do not edit by hand

#' Create a data.frame to show the zones
#' 
#' It creates the `start_borough`, `start_zone` and `start_service_zone` 
#' columns based on the `PULocationID` column and the `end_borough`, `end_zone` 
#' and `end_service_zone` columns based on the `DOLocationID` column.
#'
#' @param df A data.frame with all the code zones from main data.
#' @param zone_tb A data.frame with zones from data dictionary.
#' 
#' @importFrom data.table is.data.table `%chin%` uniqueN as.data.table
#'
#' @return A data.table
#' @export
join_zones <- function(df, zone_tb){
  
  # Validating that the tables has the columns needed
  stopifnot("df must have DOLocationID and PULocationID zone ids" = 
              all(c("DOLocationID", "PULocationID") %chin% names(df)))
  
  stopifnot("zone_tb must have LocationID, Borough, Zone and service_zone" = 
              all(c("LocationID", "Borough", "Zone", "service_zone") %chin% names(zone_tb)))
  
  # zone_tb can no have duplicated zones
  stopifnot("All zone_tb rows must be unique" = uniqueN(zone_tb$LocationID) == nrow(zone_tb))
  
  
  if(!data.table::is.data.table(df)){
    df <- data.table::as.data.table(df)
  }
  
  if(!data.table::is.data.table(zone_tb)){
    zone_tb <- data.table::as.data.table(zone_tb)
  }
  
  zone_tb[, .(end_id = LocationID,
              end_borough = Borough,
              end_zone = Zone,
              end_service_zone = service_zone)
  ][df, on = c("end_id" = "DOLocationID")
  ][, zone_tb[, .(start_id = LocationID,
                  start_borough = Borough,
                  start_zone = Zone,
                  start_service_zone = service_zone)
      ][.SD, on = c("start_id" = "PULocationID")
  ][, !c("start_id", "end_id")]]

}
