# WARNING - Generated by {fusen} from dev/flat_functions.Rmd: do not edit by hand

#' Define how to sample by group
#'
#' @param x A data frame, data frame extension (e.g. a tibble), or a lazy data frame (e.g. from dbplyr or dtplyr).
#' @param ... Variables to group by.
#' @param size Defining the number of row to sample.
#' @param seed Define a seed to keep the process reproducible
#' 
#' @importFrom data.table `:=` setDT setnames
#' @importFrom rlang quos
#' @importFrom dplyr count collect
#' @importFrom withr local_seed
#'
#' @return A data.table
#' @export
#' 
#' @examples
#'
#' data.frame(x = rep(1:5, each = 2)) |>
#'   plan_sample_by_group(x , size = 5)
#'
plan_sample_by_group <- function(x, ..., size = 1e6, seed = 1) {
  
  # Counting the rows by group
  grouping_vars_expr <- rlang::quos(...)
  counted_data <- dplyr::count(x, !!! grouping_vars_expr, name = "count")
  
  # Collecting the data and setting to DT
  if(is_arrow_con(x)){
    counted_data <- dplyr::collect(counted_data)
  }
  data.table::setDT(counted_data)
  
  # Adding a column prefix
  data.table::setnames(counted_data, paste0("group_", names(counted_data)))
  
  # The defining the proportion of each row in original data
  counted_data[,`:=`(group_pct = group_count / sum(group_count),
                     row_id = .I)]
  
  # Setting the seed to make the plan reproducible
  # without changing the global environment
  withr::local_seed(seed)
  
  # Creating the plan
  result <- 
    counted_data[, .(row_id = sample(row_id, 
                                     size = size,
                                     replace = TRUE, 
                                     prob = group_pct))
    ][, .(rows_to_sample = .N),
      by = "row_id"
    ][order(-rows_to_sample), 
      counted_data[.SD, on = "row_id"]]
  
  # Confirming if the plan is correct
  stopifnot("The result is planning to sample more rows that the available in the original data.\nTry to define a different seed" = result[group_count < rows_to_sample, .N] == 0)
  
  return(result)
}
