# WARNING - Generated by {fusen} from dev/flat_functions.Rmd: do not edit by hand

#' TrainingTrips
#'
#' Random 5% sample of taxi trips that took place in Manhattan, Brooklyn and Queens during 2022.
#'
#' @format A data.table with variables of the original data.
#' @source TLC Trip Record Data
"TrainingTrips"
