# WARNING - Generated by {fusen} from dev/flat_functions.Rmd: do not edit by hand

#' Take a sample from a parquet file
#'
#' @param file_path A character file name or URI.
#' @param valid_zones A vector of zones of the trips you want to sample from.
#' @param prob The proportion of rows to keep in the sample.
#' @param seed Number to keep the sample reprodicible.
#' 
#' @importFrom arrow read_parquet
#' @importFrom data.table setDT setkeyv
#' @importFrom withr local_seed
#'
#' @return A data.table
#' @export
#'
#' @examples
#' df <- data.frame(x = 1:100)
#' file_path <- tempfile(fileext = ".parquet")
#'
#' arrow::write_parquet(df, file_path)
#'
#' sample_parquet(file_path)
sample_parquet <- function(file_path,
                           valid_zones = NULL,
                           prob = 0.05,
                           seed = 1){
  
  
raw_data <- arrow::read_parquet(file_path)

data.table::setDT(raw_data)

withr::local_seed(seed)

if(is.null(valid_zones)) {
  
  sampled_data <-
    raw_data[, .SD[sample.int(.N, size = as.integer(.N * prob))]]
  
  return(sampled_data)
  
}

sampled_data <-
  raw_data[.(valid_zones),
           on = "PULocationID",
           nomatch = 0
  ][.(valid_zones),
    on = "DOLocationID",
    nomatch = 0
  ][, .SD[sample.int(.N, size = as.integer(.N * prob))]]

return(sampled_data)
  
}

