# WARNING - Generated by {fusen} from dev/flat_functions.Rmd: do not edit by hand

#' Apply the transformations based on initial EDA
#'
#' @param dt A data.table with columns:
#' - hvfhs_license_num
#' - dispatching_base_num
#' - originating_base_num
#' - access_a_ride_flag
#' - request_datetime
#' - dropoff_datetime
#' - driver_pay
#'
#' @export
#' 
set_initial_cleaning <- function(dt) {
  
  col_names <- names(dt)
  
  if("hvfhs_license_num" %chin% col_names){
    
    dt[, company := data.table::fcase(hvfhs_license_num == "HV0002", "Juno",
                                      hvfhs_license_num == "HV0003", "Uber",
                                      hvfhs_license_num == "HV0004", "Via",
                                      hvfhs_license_num == "HV0005", "Lyft",
                                      default = "Other")]
    
    dt[, hvfhs_license_num := NULL]
    
  }
  
  
  if("dispatching_base_num" %chin% col_names){
    
    dt[c(NA_character_, " "), 
       dispatching_base_num := "Missing",
       on = "dispatching_base_num"]
    
    dt[!c("B03404", "B03406", "Missing"), 
       dispatching_base_num := "Other",
       on = "dispatching_base_num"]
    
  }
  
  
  if("originating_base_num" %chin% col_names){
    
    dt[c(NA_character_, " "), 
       originating_base_num := "Missing",
       on = "originating_base_num"]
    
    dt[!c("B03404", "B03406", "Missing"), 
       originating_base_num := "Other",
       on = "originating_base_num"]
    
  }
  
  
  if("access_a_ride_flag" %chin% col_names){
    
    dt[c(NA_character_, " "), 
       access_a_ride_flag := "Missing",
       on = "access_a_ride_flag"]
    
  }
  
  
  n_time_columns <- sum(c("request_datetime", "dropoff_datetime") %chin% col_names)
  stopifnot("You need to provide both datetime columns" = n_time_columns != 1L)
  
  if(n_time_columns == 2L){
    
   dt[, `:=`(request_datetime = pmin(request_datetime, dropoff_datetime),
             dropoff_datetime = pmax(request_datetime, dropoff_datetime))]
    
    dt[, trip_hours := 
         difftime(dropoff_datetime,
                  request_datetime,
                  units = "mins") |>
         as.double() |>
         (\(x) x/60)()]
    
  }
  
  
  if("driver_pay" %chin% col_names){
    
    dt[driver_pay < 0, 
       driver_pay := NA_real_]
    
  }
  
  return(dt)
  
}
