# WARNING - Generated by {fusen} from dev/flat_functions.Rmd: do not edit by hand

#' Display boxplot chart based of a summary.
#'
#' @param x A data.frame
#' @param y_title A character value indicating the title to describe the y axis.
#' @param y_break_width A number to define the width related to y axis.
#' 
#' @importFrom ggplot2 ggplot geom_boxplot scale_y_continuous labs theme_light
#' @importFrom scales breaks_width
#'
#' @return A ggplot
#' @export
summary_to_boxplot <- function(x, y_title = "", y_break_width = 2) {
  
  ggplot2::ggplot(x)+
    ggplot2::geom_boxplot(
      aes(x = "", y = q2,
          ymin = pmax(min_value, lower_whisker), 
          lower = q1, 
          middle = q2, 
          upper = q3, 
          ymax = pmin(max_value, higher_whisker)),
      stat = "identity",
      width = 0.3
    )+
    ggplot2::scale_y_continuous(breaks = scales::breaks_width(y_break_width))+
    ggplot2::labs(y = y_title,
                  x = "") +
    ggplot2::theme_light()
  
}
